"use server";

import { db } from "@/lib/db";
import { blogs, clients, generatedPosts } from "@/lib/db/schema";
import { and, desc, eq, isNotNull } from "drizzle-orm";
import { requireAdmin } from "@/lib/auth/helpers";
import {
  generateContent,
  ideateTopic,
  type GenerateOptions,
  type Tone,
} from "@/lib/services/content-generator";
import { publishPost, type PlatformBlog } from "@/lib/services/platform-client";

// ─── Types ──────────────────────────────────────────────────────────────────

export interface GenerateAndPublishInput {
  blogId: string;
  topic?: string;
  keywords?: string[];
  wordCount?: number;
  tone?: Tone;
  isAutoGenerated?: boolean;
}

export interface GenerateAndPublishResult {
  success: boolean;
  generatedPostId: string;
  status: "published" | "generated" | "failed";
  externalPostId?: string | number;
  externalPostUrl?: string;
  message: string;
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function blogHasCredentials(blog: typeof blogs.$inferSelect): boolean {
  if (blog.platform === "shopify") {
    return Boolean(blog.shopifyStoreUrl && blog.shopifyAdminApiToken);
  }
  return Boolean(blog.wpUrl && blog.wpUsername && blog.wpAppPassword);
}

function isBlogDueForPost(blog: typeof blogs.$inferSelect, now: Date = new Date()): boolean {
  if (!blog.postingFrequencyDays || blog.postingFrequencyDays <= 0) return false;

  // Use lastPostVerifiedAt as the reference for "last seen post" — falls back to
  // never-posted if null.
  const last = blog.lastPostVerifiedAt;
  if (!last) return true;

  const dayMs = 1000 * 60 * 60 * 24;
  const daysSince = (now.getTime() - last.getTime()) / dayMs;
  return daysSince >= blog.postingFrequencyDays;
}

async function getRecentTitles(blogId: string, limit = 20): Promise<string[]> {
  const rows = await db
    .select({ title: generatedPosts.title })
    .from(generatedPosts)
    .where(eq(generatedPosts.blogId, blogId))
    .orderBy(desc(generatedPosts.createdAt))
    .limit(limit);
  return rows.map((r) => r.title).filter((t): t is string => Boolean(t));
}

// ─── Core: generate + publish for one blog ──────────────────────────────────

async function runGenerateAndPublish(
  input: GenerateAndPublishInput,
): Promise<GenerateAndPublishResult> {
  // 1. Load blog + client (for niche)
  const [row] = await db
    .select({
      blog: blogs,
      clientNiche: clients.niche,
    })
    .from(blogs)
    .innerJoin(clients, eq(blogs.clientId, clients.id))
    .where(eq(blogs.id, input.blogId))
    .limit(1);

  if (!row) throw new Error(`Blog ${input.blogId} not found`);
  const { blog, clientNiche } = row;

  if (!blogHasCredentials(blog)) {
    throw new Error(
      `Blog ${blog.domain} is missing ${blog.platform} credentials — connect the platform first`,
    );
  }

  // 2. Resolve topic + keywords (auto-ideate if not supplied)
  let topic = input.topic?.trim();
  let keywords = input.keywords ?? [];

  if (!topic) {
    const recentTitles = await getRecentTitles(blog.id);
    const ideated = await ideateTopic(clientNiche, recentTitles);
    topic = ideated.topic;
    if (keywords.length === 0) keywords = ideated.keywords;
  }

  if (!topic) throw new Error("Could not resolve a topic to write about");

  // 3. Insert pending row to track the attempt
  const [pending] = await db
    .insert(generatedPosts)
    .values({
      blogId: blog.id,
      clientId: blog.clientId,
      topic,
      keywords,
      status: "generating",
      isAutoGenerated: input.isAutoGenerated ?? false,
    })
    .returning({ id: generatedPosts.id });

  const generatedPostId = pending.id;

  try {
    // 4. Generate content
    const genOpts: GenerateOptions = {
      topic,
      keywords,
      wordCount: input.wordCount ?? 1000,
      tone: input.tone ?? "professional",
      niche: clientNiche,
      seoOptimized: true,
    };
    const content = await generateContent(genOpts);

    await db
      .update(generatedPosts)
      .set({
        status: "publishing",
        title: content.title,
        body: content.content,
        excerpt: content.excerpt,
        metaTitle: content.metaTitle,
        metaDescription: content.metaDescription,
        keywords: content.keywords,
        wordCount: content.wordCount,
        seoScore: content.seoScore,
        readabilityScore: content.readabilityScore,
        brandVoiceScore: content.brandVoiceScore,
        tokensUsed: content.tokensUsed,
        costUsd: content.costUsd.toString(),
        generatedAt: new Date(),
        updatedAt: new Date(),
      })
      .where(eq(generatedPosts.id, generatedPostId));

    // 5. Publish via platform-client (handles WP + Shopify)
    const platformBlog: PlatformBlog = {
      platform: blog.platform,
      wpUrl: blog.wpUrl,
      wpUsername: blog.wpUsername,
      wpAppPassword: blog.wpAppPassword,
      shopifyStoreUrl: blog.shopifyStoreUrl,
      shopifyAdminApiToken: blog.shopifyAdminApiToken,
      shopifyApiVersion: blog.shopifyApiVersion,
      shopifyBlogId: blog.shopifyBlogId,
    };

    const publish = await publishPost(platformBlog, {
      title: content.title,
      content: content.content,
      excerpt: content.excerpt,
      status: "publish",
      tags: content.keywords,
    });

    if (!publish.success) {
      await db
        .update(generatedPosts)
        .set({
          status: "generated",
          failureReason: `Publish failed: ${publish.message}`,
          updatedAt: new Date(),
        })
        .where(eq(generatedPosts.id, generatedPostId));

      return {
        success: false,
        generatedPostId,
        status: "generated",
        message: `Generated but publish failed: ${publish.message}`,
      };
    }

    // 6. Mark published, update blog's last-post tracking
    const publishedAt = new Date();
    await db
      .update(generatedPosts)
      .set({
        status: "published",
        externalPostId: publish.postId != null ? String(publish.postId) : null,
        externalPostUrl: publish.postUrl ?? null,
        publishedAt,
        updatedAt: publishedAt,
      })
      .where(eq(generatedPosts.id, generatedPostId));

    await db
      .update(blogs)
      .set({
        lastPostVerifiedAt: publishedAt,
        lastPostTitle: content.title,
        updatedAt: publishedAt,
      })
      .where(eq(blogs.id, blog.id));

    return {
      success: true,
      generatedPostId,
      status: "published",
      externalPostId: publish.postId,
      externalPostUrl: publish.postUrl,
      message: `Published "${content.title}" to ${blog.domain}`,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    await db
      .update(generatedPosts)
      .set({
        status: "failed",
        failureReason: message,
        updatedAt: new Date(),
      })
      .where(eq(generatedPosts.id, generatedPostId));

    return {
      success: false,
      generatedPostId,
      status: "failed",
      message,
    };
  }
}

// ─── Public actions ─────────────────────────────────────────────────────────

/** Admin-triggered manual generate-and-publish for a single blog. */
export async function generateAndPublishForBlog(
  input: GenerateAndPublishInput,
): Promise<GenerateAndPublishResult> {
  await requireAdmin();
  return runGenerateAndPublish(input);
}

/** Cron-triggered sweep. Generates+publishes for every active blog whose
 * postingFrequencyDays interval has elapsed since the last seen post. */
export async function runAutoPublishCron(): Promise<{
  considered: number;
  due: number;
  published: number;
  failed: number;
  results: Array<{ blogId: string; domain: string; status: string; message: string }>;
}> {
  const activeBlogs = await db
    .select()
    .from(blogs)
    .where(and(eq(blogs.status, "active"), isNotNull(blogs.postingFrequencyDays)));

  const now = new Date();
  const dueBlogs = activeBlogs.filter((b) => isBlogDueForPost(b, now) && blogHasCredentials(b));

  let published = 0;
  let failed = 0;
  const results: Array<{ blogId: string; domain: string; status: string; message: string }> = [];

  for (const blog of dueBlogs) {
    try {
      const result = await runGenerateAndPublish({
        blogId: blog.id,
        isAutoGenerated: true,
      });
      if (result.status === "published") published++;
      else failed++;
      results.push({
        blogId: blog.id,
        domain: blog.domain,
        status: result.status,
        message: result.message,
      });
    } catch (error) {
      failed++;
      const message = error instanceof Error ? error.message : "Unknown error";
      console.error(`Auto-publish failed for ${blog.domain}:`, error);
      results.push({ blogId: blog.id, domain: blog.domain, status: "failed", message });
    }
  }

  return {
    considered: activeBlogs.length,
    due: dueBlogs.length,
    published,
    failed,
    results,
  };
}
