"use server";

import { db } from "@/lib/db";
import { blogs, clients, generatedPosts } from "@/lib/db/schema";
import { and, desc, eq, gte, isNotNull, or, sql } from "drizzle-orm";
import { requireAdmin } from "@/lib/auth/helpers";
import {
  generateContent,
  ideateTopic,
  type GenerateOptions,
  type Tone,
} from "@/lib/services/content-generator";
import { publishPost, type PlatformBlog } from "@/lib/services/platform-client";

// ─── Types ──────────────────────────────────────────────────────────────────

export interface GenerateAndPublishInput {
  blogId: string;
  topic?: string;
  keywords?: string[];
  wordCount?: number;
  tone?: Tone;
  isAutoGenerated?: boolean;
}

export interface GenerateAndPublishResult {
  success: boolean;
  generatedPostId: string;
  status: "published" | "generated" | "failed";
  externalPostId?: string | number;
  externalPostUrl?: string;
  message: string;
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function blogHasCredentials(blog: typeof blogs.$inferSelect): boolean {
  if (blog.platform === "shopify") {
    return Boolean(blog.shopifyStoreUrl && blog.shopifyAdminApiToken);
  }
  return Boolean(blog.wpUrl && blog.wpUsername && blog.wpAppPassword);
}

/** Start of the current UTC day (used for the per-day cap). */
function startOfUtcDay(now: Date): Date {
  return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
}

/** Reason a blog is or isn't due. The string is what the cron reports. */
type DueDecision =
  | { due: true }
  | { due: false; reason: string };

/**
 * Cadence eligibility — does NOT check the per-client total cap (that needs a
 * separate query, done in runAutoPublishCron).
 *
 * Logic:
 *   - If postsPerDay set: today's count must be < postsPerDay.
 *     If postingIntervalHours also set: lastPostVerifiedAt must be >= that many
 *     hours ago. If not set, defaults to 24/postsPerDay (even spacing).
 *   - Else if postingFrequencyDays set: lastPostVerifiedAt must be >= that many
 *     days ago.
 *   - Else: not auto-publishable.
 */
function isBlogDueForPost(
  blog: typeof blogs.$inferSelect,
  todaysPublishedCount: number,
  now: Date = new Date(),
): DueDecision {
  const last = blog.lastPostVerifiedAt;
  const hour = 1000 * 60 * 60;

  if (blog.postsPerDay && blog.postsPerDay > 0) {
    if (todaysPublishedCount >= blog.postsPerDay) {
      return {
        due: false,
        reason: `daily cap hit (${todaysPublishedCount}/${blog.postsPerDay} today)`,
      };
    }
    if (last) {
      const intervalHours =
        blog.postingIntervalHours && blog.postingIntervalHours > 0
          ? blog.postingIntervalHours
          : Math.floor(24 / blog.postsPerDay);
      const hoursSince = (now.getTime() - last.getTime()) / hour;
      if (hoursSince < intervalHours) {
        return {
          due: false,
          reason: `${hoursSince.toFixed(1)}h since last post < ${intervalHours}h interval`,
        };
      }
    }
    return { due: true };
  }

  if (blog.postingFrequencyDays && blog.postingFrequencyDays > 0) {
    if (!last) return { due: true };
    const daysSince = (now.getTime() - last.getTime()) / (24 * hour);
    if (daysSince < blog.postingFrequencyDays) {
      return {
        due: false,
        reason: `${daysSince.toFixed(2)}d since last post < ${blog.postingFrequencyDays}d`,
      };
    }
    return { due: true };
  }

  return { due: false, reason: "no cadence configured (postsPerDay/postingFrequencyDays unset)" };
}

async function getRecentTitles(blogId: string, limit = 20): Promise<string[]> {
  const rows = await db
    .select({ title: generatedPosts.title })
    .from(generatedPosts)
    .where(eq(generatedPosts.blogId, blogId))
    .orderBy(desc(generatedPosts.createdAt))
    .limit(limit);
  return rows.map((r) => r.title).filter((t): t is string => Boolean(t));
}

// ─── Core: generate + publish for one blog ──────────────────────────────────

async function runGenerateAndPublish(
  input: GenerateAndPublishInput,
): Promise<GenerateAndPublishResult> {
  // 1. Load blog + client (for niche)
  const [row] = await db
    .select({
      blog: blogs,
      clientNiche: clients.niche,
    })
    .from(blogs)
    .innerJoin(clients, eq(blogs.clientId, clients.id))
    .where(eq(blogs.id, input.blogId))
    .limit(1);

  if (!row) throw new Error(`Blog ${input.blogId} not found`);
  const { blog, clientNiche } = row;

  if (!blogHasCredentials(blog)) {
    throw new Error(
      `Blog ${blog.domain} is missing ${blog.platform} credentials — connect the platform first`,
    );
  }

  // 2. Resolve topic + keywords (auto-ideate if not supplied)
  let topic = input.topic?.trim();
  let keywords = input.keywords ?? [];

  if (!topic) {
    const recentTitles = await getRecentTitles(blog.id);
    const ideated = await ideateTopic(clientNiche, recentTitles);
    topic = ideated.topic;
    if (keywords.length === 0) keywords = ideated.keywords;
  }

  if (!topic) throw new Error("Could not resolve a topic to write about");

  // 3. Insert pending row to track the attempt
  const [pending] = await db
    .insert(generatedPosts)
    .values({
      blogId: blog.id,
      clientId: blog.clientId,
      topic,
      keywords,
      status: "generating",
      isAutoGenerated: input.isAutoGenerated ?? false,
    })
    .returning({ id: generatedPosts.id });

  const generatedPostId = pending.id;

  try {
    // 4. Generate content
    const genOpts: GenerateOptions = {
      topic,
      keywords,
      wordCount: input.wordCount ?? 1000,
      tone: input.tone ?? "professional",
      niche: clientNiche,
      seoOptimized: true,
    };
    const content = await generateContent(genOpts);

    await db
      .update(generatedPosts)
      .set({
        status: "publishing",
        title: content.title,
        body: content.content,
        excerpt: content.excerpt,
        metaTitle: content.metaTitle,
        metaDescription: content.metaDescription,
        keywords: content.keywords,
        wordCount: content.wordCount,
        seoScore: content.seoScore,
        readabilityScore: content.readabilityScore,
        brandVoiceScore: content.brandVoiceScore,
        tokensUsed: content.tokensUsed,
        costUsd: content.costUsd.toString(),
        generatedAt: new Date(),
        updatedAt: new Date(),
      })
      .where(eq(generatedPosts.id, generatedPostId));

    // 5. Publish via platform-client (handles WP + Shopify)
    const platformBlog: PlatformBlog = {
      platform: blog.platform,
      wpUrl: blog.wpUrl,
      wpUsername: blog.wpUsername,
      wpAppPassword: blog.wpAppPassword,
      shopifyStoreUrl: blog.shopifyStoreUrl,
      shopifyAdminApiToken: blog.shopifyAdminApiToken,
      shopifyApiVersion: blog.shopifyApiVersion,
      shopifyBlogId: blog.shopifyBlogId,
    };

    const publish = await publishPost(platformBlog, {
      title: content.title,
      content: content.content,
      excerpt: content.excerpt,
      status: "publish",
      tags: content.keywords,
    });

    if (!publish.success) {
      await db
        .update(generatedPosts)
        .set({
          status: "generated",
          failureReason: `Publish failed: ${publish.message}`,
          updatedAt: new Date(),
        })
        .where(eq(generatedPosts.id, generatedPostId));

      return {
        success: false,
        generatedPostId,
        status: "generated",
        message: `Generated but publish failed: ${publish.message}`,
      };
    }

    // 6. Mark published, update blog's last-post tracking
    const publishedAt = new Date();
    await db
      .update(generatedPosts)
      .set({
        status: "published",
        externalPostId: publish.postId != null ? String(publish.postId) : null,
        externalPostUrl: publish.postUrl ?? null,
        publishedAt,
        updatedAt: publishedAt,
      })
      .where(eq(generatedPosts.id, generatedPostId));

    await db
      .update(blogs)
      .set({
        lastPostVerifiedAt: publishedAt,
        lastPostTitle: content.title,
        updatedAt: publishedAt,
      })
      .where(eq(blogs.id, blog.id));

    return {
      success: true,
      generatedPostId,
      status: "published",
      externalPostId: publish.postId,
      externalPostUrl: publish.postUrl,
      message: `Published "${content.title}" to ${blog.domain}`,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    await db
      .update(generatedPosts)
      .set({
        status: "failed",
        failureReason: message,
        updatedAt: new Date(),
      })
      .where(eq(generatedPosts.id, generatedPostId));

    return {
      success: false,
      generatedPostId,
      status: "failed",
      message,
    };
  }
}

// ─── Public actions ─────────────────────────────────────────────────────────

/** Admin-triggered manual generate-and-publish for a single blog. */
export async function generateAndPublishForBlog(
  input: GenerateAndPublishInput,
): Promise<GenerateAndPublishResult> {
  await requireAdmin();
  return runGenerateAndPublish(input);
}

export interface AutoPublishResult {
  considered: number;
  due: number;
  published: number;
  failed: number;
  skipped: number;
  results: Array<{
    blogId: string;
    domain: string;
    status: "published" | "generated" | "failed" | "skipped";
    message: string;
  }>;
}

/**
 * Cron-triggered sweep. For every active blog with a cadence configured:
 *   1. Skip if the client's lifetime published-post count >= clients.totalBlogsTarget
 *      (when totalBlogsTarget > 0).
 *   2. Skip if the blog isn't due (per-day cap or min interval not satisfied).
 *   3. Otherwise generate + publish one post.
 *
 * Counts are tracked in-memory across the loop so two due blogs sharing a
 * client don't both punch through the cap on the same run.
 */
export async function runAutoPublishCron(): Promise<AutoPublishResult> {
  const now = new Date();
  const todayStart = startOfUtcDay(now);

  // Active blogs with at least one cadence field set, joined with their client
  // for niche + total cap.
  const rows = await db
    .select({
      blog: blogs,
      clientNiche: clients.niche,
      clientTarget: clients.totalBlogsTarget,
    })
    .from(blogs)
    .innerJoin(clients, eq(blogs.clientId, clients.id))
    .where(
      and(
        eq(blogs.status, "active"),
        or(isNotNull(blogs.postsPerDay), isNotNull(blogs.postingFrequencyDays)),
      ),
    );

  // Per-client lifetime published count (used for totalBlogsTarget cap).
  const clientCounts = await db
    .select({
      clientId: generatedPosts.clientId,
      n: sql<number>`count(*)::int`,
    })
    .from(generatedPosts)
    .where(eq(generatedPosts.status, "published"))
    .groupBy(generatedPosts.clientId);
  const publishedByClient = new Map(clientCounts.map((r) => [r.clientId, r.n]));

  // Per-blog count of posts already published today (for postsPerDay cap).
  const blogCountsToday = await db
    .select({
      blogId: generatedPosts.blogId,
      n: sql<number>`count(*)::int`,
    })
    .from(generatedPosts)
    .where(
      and(
        eq(generatedPosts.status, "published"),
        gte(generatedPosts.publishedAt, todayStart),
      ),
    )
    .groupBy(generatedPosts.blogId);
  const publishedTodayByBlog = new Map(blogCountsToday.map((r) => [r.blogId, r.n]));

  let published = 0;
  let failed = 0;
  let skipped = 0;
  const results: AutoPublishResult["results"] = [];

  for (const { blog, clientTarget } of rows) {
    const todayCount = publishedTodayByBlog.get(blog.id) ?? 0;
    const clientCount = publishedByClient.get(blog.clientId) ?? 0;

    // 1. Per-client total cap (clients.totalBlogsTarget acts as "total posts").
    if (clientTarget && clientTarget > 0 && clientCount >= clientTarget) {
      skipped++;
      results.push({
        blogId: blog.id,
        domain: blog.domain,
        status: "skipped",
        message: `client cap hit (${clientCount}/${clientTarget} total posts)`,
      });
      continue;
    }

    // 2. Cadence eligibility.
    const decision = isBlogDueForPost(blog, todayCount, now);
    if (!decision.due) {
      skipped++;
      results.push({
        blogId: blog.id,
        domain: blog.domain,
        status: "skipped",
        message: decision.reason,
      });
      continue;
    }

    // 3. Credential check.
    if (!blogHasCredentials(blog)) {
      skipped++;
      results.push({
        blogId: blog.id,
        domain: blog.domain,
        status: "skipped",
        message: `missing ${blog.platform} credentials`,
      });
      continue;
    }

    // 4. Run.
    try {
      const result = await runGenerateAndPublish({
        blogId: blog.id,
        isAutoGenerated: true,
      });
      results.push({
        blogId: blog.id,
        domain: blog.domain,
        status: result.status,
        message: result.message,
      });
      if (result.status === "published") {
        published++;
        // Update in-memory counters so subsequent blogs in this run see the
        // correct caps.
        publishedTodayByBlog.set(blog.id, todayCount + 1);
        publishedByClient.set(blog.clientId, clientCount + 1);
      } else {
        failed++;
      }
    } catch (error) {
      failed++;
      const message = error instanceof Error ? error.message : "Unknown error";
      console.error(`Auto-publish failed for ${blog.domain}:`, error);
      results.push({ blogId: blog.id, domain: blog.domain, status: "failed", message });
    }
  }

  return {
    considered: rows.length,
    due: published + failed,
    published,
    failed,
    skipped,
    results,
  };
}
